eventcalendar/urls.py
from django.conf.urls import patterns, url
import views


urlpatterns = patterns('',
    # url(
    #     r'^$',
    #     views.OccurrenceList.as_view(),
    #     name='eventcalendar-index'
    # ),
    url(
        r'^$',
        views.OccurrenceSearchView.as_view(),
        name='eventcalendar-index'
    ),
    url(
        r'^parse/$',
        views.parsable,
        name='eventcalendar-parsable',
    ),
    url(
        r'^venues/$',
        views.VenueList.as_view(),
        name='eventcalendar-venue-list'
    ),
    url(
        r'^event/add/$',
        views.EventCreate.as_view(),
        name='eventcalendar-add-event'
    ),
    url(
        r'^event/(?P<slug>[-\w]+)/$',
        views.EventView.as_view(),
        name='eventcalendar-event'
    ),
    url(
        r'^event/(?P<slug>[-\w]+)/edit/$',
        views.EventUpdate.as_view(),
        name='eventcalendar-edit-event'
    ),
    url(
        r'^event/(?P<slug>[-\w]+)/delete/$',
        views.EventDelete.as_view(),
        name='eventcalendar-delete-event'
    ),
    url(
        r'^(?P<slug>[\w-]+)/$',
        views.EventCategoryDetail.as_view(),
        name='eventcalendar-category'
    ),
    # url(
    #     r'^(?P<slug>[-\w]+)/(\d+)/$',
    #     views.occurrence_view,
    #     name='eventcalendar-occurrence'
    # ),
)

eventcalendar/forms.py
"""
Convenience forms for adding and updating ``Event`` and ``Occurrence``s.

"""
from __future__ import print_function, unicode_literals

from django import VERSION
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify
from django.forms.utils import to_current_timezone

from django_hstore.forms import DictionaryField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, HTML
from haystack.forms import FacetedSearchForm

from .settings import TIMESLOT_INTERVAL, DEFAULT_OCCURRENCE_DURATION
from .models import Event, Schedule, Venue
from .fields import SliderWidget, RangeField, FrontEndHStoreWidget, ClearableWidget
import utils

FIELDS_REQUIRED = (VERSION[:2] >= (1, 6))
MINUTES_INTERVAL = TIMESLOT_INTERVAL.seconds // 60
SECONDS_INTERVAL = utils.time_delta_total_seconds(DEFAULT_OCCURRENCE_DURATION)


class CustomSplitDateTimeWidget(forms.MultiWidget):
    """
    A Widget that splits datetime input into two <input type="text"> boxes.
    """
    supports_microseconds = False

    def __init__(self, attrs=None, date_format=None, time_format=None):
        date_attrs = attrs or {}
        time_attrs = attrs or {}
        date_attrs['type'] = 'text'
        date_attrs['data-ng-datepicker'] = ''
        time_attrs['type'] = 'text'
        time_attrs['data-ng-timepicker'] = "{format: '12h'}"

        widgets = (forms.DateInput(attrs=date_attrs, format=date_format),
                   forms.TimeInput(attrs=time_attrs, format=time_format))
        super(CustomSplitDateTimeWidget, self).__init__(widgets, attrs)

    def decompress(self, value):
        if value:
            value = to_current_timezone(value)
            return [value.date(), value.time().replace(microsecond=0)]
        return [None, None]


class MultipleIntegerField(forms.MultipleChoiceField):
    """
    A form field for handling multiple integers.

    """
    def __init__(self, choices, size=None, label=None, widget=None):
        if widget is None:
            widget = forms.SelectMultiple(attrs={'size': size or len(choices)})
        super(MultipleIntegerField, self).__init__(
            required=False,
            choices=choices,
            label=label,
            widget=widget,
        )

    def clean(self, value):
        return [int(i) for i in super(MultipleIntegerField, self).clean(value)]


class ScheduleFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(ScheduleFormHelper, self).__init__(*args, **kwargs)
        self.form_method = 'post'
        self.form_tag = False
        self.recurring_id = "id_schedules-__prefix__-recurring"
        self.layout = Layout(
            'id',
            Fieldset(
                'Date and Time Information',
                'begins',
                'duration',
            ),
            Fieldset(
                'Optional Recurring Options',
                HTML("""<div class="ng-grid"><div class="ng-width-6-10">"""),
                'schedule_text',
                'rrule_str',
                HTML("""<p>Examples:</p><ul class="ng-list ng-list-bullet">
                    <li>Every weekday</li>
                    <li>Every 2 weeks on Tuesday</li>
                    <li>Every week on Monday, Wednesday</li>
                    <li>Every month on the 2nd last Friday for 7 times</li>
                    <li>Every 6 months</li></ul>"""),
                HTML("""</div>
                        <div class="ng-width-4-10">
                            <fieldset>
                                <legend class="ng-padding-small-bottom">Schedule Dates</legend>
                                <ul class="schedule-dates ng-list ng-list-striped">
                                </ul>
                            </fieldset>
                        </div>
                    </div>"""),
                css_id=self.recurring_id
            ),
        )


class ScheduleForm(forms.ModelForm):
    """
    Schedule Form with just a text field
    """
    begins = forms.SplitDateTimeField(
        label=_('Begins'),
        widget=CustomSplitDateTimeWidget())
    duration = forms.DecimalField(
        label=_("Duration in hours"),
        widget=SliderWidget(
            min_value=0,
            max_value=24,
            attrs={
                'data-step': '0.5',
                'data-grid-num': '6',
            }),
        initial=1
    )
    schedule_text = forms.CharField(
        label="Type in the recurring schedule",
        widget=forms.TextInput(),
        required=False)
    rrule_str = forms.CharField(
        widget=forms.HiddenInput(),
        required=False)

    class Meta:
        model = Schedule
        fields = '__all__'

    class Media:
        js = ('eventcalendar/nlp.js', 'eventcalendar/rrule.js', )


class EventForm(forms.ModelForm):
    """
    A simple form for adding and updating Event attributes
    """
    required_css_class = "ng-form-required"
    error_css_class = "ng-form-danger"
    id = forms.CharField(widget=forms.HiddenInput(), required=False)
    more_info_url = forms.URLField(widget=forms.TextInput(), required=False)
    tickets_url = forms.URLField(widget=forms.TextInput(), required=False)
    min_age = forms.IntegerField(widget=forms.HiddenInput(), required=False, initial=0)
    max_age = forms.IntegerField(widget=forms.HiddenInput(), required=False, initial=100)
    age_range = RangeField(forms.IntegerField, min_value=0, max_value=100, required=False)
    price_info = DictionaryField(widget=FrontEndHStoreWidget, required=False, help_text="Give each price a label for the price such as &lsquo;Adult&rsquo; or &lsquo;Matinee&rsquo;.")
    location_name = forms.CharField(required=False, widget=ClearableWidget(attrs={'class': "textinput textInput ng-width-1-1"}))
    raw_location = forms.CharField(label="Location address", required=True)
    venue = forms.ModelChoiceField(
        queryset=Venue.objects.all(),
        widget=forms.HiddenInput,
        required=False)

    class Meta:
        model = Event
        fields = (
            "id", "title", "category", "description", "location_name", "raw_location",
            "venue", "image",
            "age_range", "more_info_url", "tickets_url", "price_info",
            "min_age", "max_age")

    def __init__(self, *args, **kwargs):
        if 'instance' in kwargs and kwargs['instance']:
            kwargs['initial']['age_range'] = "%s;%s" % (kwargs['instance'].min_age, kwargs['instance'].max_age, )
        super(EventForm, self).__init__(*args, **kwargs)
        self.form_helper = FormHelper()
        self.form_helper.form_tag = False
        self.form_helper.layout = Layout(
            'id',
            Fieldset(
                'Event Information',
                'id',
                'title',
                'category',
                'description'),
            Fieldset(
                'Location Information',
                'location_name',
                'raw_location',
                'venue'),
            Fieldset(
                'Additional Information',
                'more_info_url',
                'tickets_url',
                'price_info',
                'age_range',
                'image',
                'min_age',
                'max_age',
            )
        )

    def clean(self):
        cleaned_data = super(EventForm, self).clean()
        title = cleaned_data.get('title', '')
        cleaned_data['slug'] = slugify(title)
        return cleaned_data


class OccurrenceSearchForm(FacetedSearchForm):
    start_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'type': 'date'}))
    end_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'type': 'date'}))
    address = forms.CharField(required=False)
    distance = forms.ChoiceField(
        choices=(
            ('5', '5 miles'),
            ('10', '10 miles'),
            ('25', '25 miles'),
            ('50', '50 miles'),
        ),
        initial='5',
        required=False
    )
    use_current_location = forms.BooleanField(required=False, initial=False)
    latitude = forms.CharField(required=False, widget=forms.HiddenInput)
    longitude = forms.CharField(required=False, widget=forms.HiddenInput)
    neighborhoods = forms.MultipleChoiceField(
        required=False,
        choices=()
    )
    categories = forms.MultipleChoiceField(
        required=False,
        choices=()
    )
    # sorting = forms.ChoiceField(
    #     choices=(
    #         ('start_time', 'Date'),
    #         ('proximity', 'Proximity'),
    #         ('-score', 'Relevance'), ),
    #     initial='start_time',
    #     required=False,
    #     widget=forms.HiddenInput
    # )

    def __init__(self, *args, **kwargs):
        super(OccurrenceSearchForm, self).__init__(*args, **kwargs)

        # Setup dynamic choices
        from .models import Neighborhood, EventCategory
        from django.core.cache import caches
        cache = caches['default']
        neighborhoods = cache.get('eventcalendar_neighborhoods')
        if not neighborhoods:
            neighborhoods = list(Neighborhood.objects.values_list('slug', 'name'))
            cache.set('eventcalendar_neighborhoods', neighborhoods, 3600)
        categories = cache.get('eventcalendar_categories')
        if not categories:
            categories = list(EventCategory.objects.values_list('slug', 'name'))
            cache.set('eventcalendar_neighborhoods', categories, 3600)
        self.fields['neighborhoods'].choices = neighborhoods
        self.fields['categories'].choices = categories

        # Set up faceting
        self.searchqueryset = self.searchqueryset.order_by('start_time')
        self.searchqueryset = self.searchqueryset.facet('neighborhood')
        self.searchqueryset = self.searchqueryset.facet('category')
        self.location = None

    def no_query_found(self):
        """
        Determines the behavior when no query was found.

eventcalendar/templates/eventcalendar/_form_row.html
{% load eventcalendar_tags %}
  <div class="ng-form-row {{ field.css_classes }}">
    {{ field.label_tag|add_class:"ng-form-label" }}
    {% if field.help_text %}
    <p class="ng-form-help-block">{{ field.help_text }}</p>
    {% endif %}
    {% if field.errors %}
    <p class="ng-text-danger">{{ field.errors|join:"<br \>" }}</p>
    {% endif %}
    {% if field.name == "start_date" %}
        <div class="ng-form-icon">
            <i class="ng-icon-calendar"></i>
    {% endif %}
    {{ field|add_class:"ng-form-control ng-width-1-1" }}
    {% if field.name == "start_date" %}
        </div>
    {% endif %}
  </div>

eventcalendar/templates/eventcalendar/_inline.html
{% load i18n admin_urls admin_static %}
<div class="inline-group" id="{{ formset.prefix }}-group">
{{ formset.management_form }}
{{ formset.non_form_errors }}

{% for form in formset %}<div class="inline-related{% if forloop.last %} empty-form last-related{% endif %}" id="{{ formset.formset.prefix }}-{% if not forloop.last %}{{ forloop.counter0 }}{% else %}empty{% endif %}">

  {% if form.form.non_field_errors %}{{ form.form.non_field_errors }}{% endif %}
  {% for field in form.visible_fields %}
    {% include "eventcalendar/_form_row.html" %}
  {% endfor %}
  {% if form.needs_explicit_pk_field %}{{ form.pk_field.field }}{% endif %}
  {{ form.fk_field.field }}
</div>{% endfor %}

<div class="inline-related empty-form last-related" id="{{ formset.prefix }}-empty">
  {% for field in formset.empty_form.hidden_fields %}
    {{ field }}
  {% endfor %}
  {% for field in formset.empty_form.visible_fields %}
    {% include "eventcalendar/_form_row.html" %}
  {% endfor %}
  {{ form.fk_field.field }}
</div>
</div>
<script type="text/javascript">
(function($) {
  $("#{{ formset.prefix|escapejs }}-group .inline-related").stackedFormset({
    prefix: "{{ formset.prefix|escapejs }}",
    deleteText: "{% filter escapejs %}{% trans "Remove" %}{% endfilter %}",
    addText: "{% filter escapejs %}{% blocktrans with verbose_name=formset.opts.verbose_name|capfirst %}Add another {{ verbose_name }}{% endblocktrans %}{% endfilter %}"
  });
})($);
</script>

eventcalendar/templates/eventcalendar/_schedule_inline.html
{% load i18n admin_urls admin_static %}
{% load crispy_forms_tags eventcalendar_tags %}

{# Variables: empty #}

<div class="inline-related ng-panel ng-panel-box-secondary{% if empty %} empty-form last-related{% endif %}" id="{{ formset.prefix|replace:"__prefix__|" }}{% if empty %}empty{% endif %}">
    <h4 class="ng-panel-title">Schedule <span class="inline_label">#{{ forloop.counter }}{% if empty %}0{% endif %}</span></h4>
    {% crispy formset schedule_helper %}
</div>

eventcalendar/templates/eventcalendar/_schedule_inline_old.html
{% load i18n admin_urls admin_static %}
{% load eventcalendar_tags %}
<div class="inline-group" id="{{ formset.prefix }}-group">
{{ formset.management_form }}
{{ formset.non_form_errors }}
{% for form in formset %}<div class="inline-related{% if forloop.last %} empty-form last-related{% endif %}" id="{{ formset.formset.prefix }}-{% if not forloop.last %}{{ forloop.counter0 }}{% else %}empty{% endif %}">

  {% if form.form.non_field_errors %}{{ form.form.non_field_errors }}{% endif %}
  {% for field in form.visible_fields %}
    {% if field.name == 'start_date' or field.name == 'start_time' or field.name == 'end_time' %}
      {% if field.name == "start_date" %}
      <div class="ng-grid">
      {% endif %}
        <div class="ng-width-1-3"><div class="ng-form-row {{ field.css_classes }}">
          {{ field.label_tag|add_class:"ng-form-label" }}
          {% if field.help_text %}
            <p class="ng-form-help-block">{{ field.help_text }}</p>
          {% endif %}
          {% if field.errors %}
            <p class="ng-text-danger">{{ field.errors|join:"<br \>" }}</p>
          {% endif %}
          {% if field.name == "start_date" %}
            <div class="ng-form-icon">
              <i class="ng-icon-calendar"></i>
          {% endif %}
          {{ field|add_class:"ng-form-control ng-width-1-1" }}
          {% if field.name == "start_date" %}
            </div>
          {% endif %}
      {% if field.name == "end_time" %}
      </div>
      {% endif %}
      </div></div>
    {% else %}
      {% include "eventcalendar/_form_row.html" %}
    {% endif %}
  {% endfor %}
  {% if form.needs_explicit_pk_field %}{{ form.pk_field.field }}{% endif %}
  {{ form.fk_field.field }}
</div>{% endfor %}

<div class="inline-related empty-form last-related" id="{{ formset.prefix }}-empty">
  {% for field in formset.empty_form.hidden_fields %}
    {{ field }}
  {% endfor %}
  {% for field in formset.empty_form.visible_fields %}
    {% if field.name == 'start_date' or field.name == 'start_time' or field.name == 'end_time' %}
        <div class="ng-form-row ng-width-1-3 {{ field.css_classes }}">
          {{ field.label_tag|add_class:"ng-form-label" }}
          {% if field.help_text %}
            <p class="ng-form-help-block">{{ field.help_text }}</p>
          {% endif %}
          {% if field.errors %}
            <p class="ng-text-danger">{{ field.errors|join:"<br \>" }}</p>
          {% endif %}
          {% if field.name == "start_date" %}
            <div class="ng-form-icon">
              <i class="ng-icon-calendar"></i>
          {% endif %}
          {{ field|add_class:"ng-form-control ng-width-1-1" }}
          {% if field.name == "start_date" %}
            </div>
          {% endif %}
      </div>
    {% else %}
      {% include "eventcalendar/_form_row.html" %}
    {% endif %}
  {% endfor %}
  {{ form.fk_field.field }}
</div>
</div>
<script type="text/javascript">
(function($) {
  $("#{{ formset.prefix|escapejs }}-group .inline-related").stackedFormset({
    prefix: "{{ formset.prefix|escapejs }}",
    deleteText: "{% filter escapejs %}{% trans "Remove" %}{% endfilter %}",
    addText: "{% filter escapejs %}{% blocktrans with verbose_name=formset.opts.verbose_name|capfirst %}Add another {{ verbose_name }}{% endblocktrans %}{% endfilter %}"
  });
})($);
</script>

eventcalendar/templates/eventcalendar/bad_user.html
{% extends "eventcalendar/base.html" %}
{% block body %}
    <p>You do not have permission to edit this event</p>
{% endblock body %}

eventcalendar/templates/eventcalendar/base.html
{% extends "site_base.html" %}

eventcalendar/templates/eventcalendar/edit_occurrence.html
{% extends "schedule/event_form_base.html" %}
{% load i18n %}

{% block body %}
<b>{% trans "Create or change occurrence. All fields are required." %}</b>
<br/><br/>
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <br/>
  <input type="submit" value="{% trans "Save" %}">
  <input type="button" value="{% trans "Cancel" %}" onclick="window.location='{{next}}'"/>
  <input type="hidden" name="next" value="{{next|default:""}}"/>
</form>
{% endblock %}

eventcalendar/templates/eventcalendar/event_confirm_delete.html
{% extends "eventcalendar/base.html" %}
{% load i18n %}

{% block body %}
    <div class="ng-width-medium-1-2 ng-container-center">
        <div class="ng-panel ng-panel-box">
            <form action="" class="ng-form" method="post">{% csrf_token %}
                <h3 class="ng-panel-title">{% trans "Delete" %}</h3>

                {% blocktrans %}Are you sure that you really want to delete &lsquo;{{ object }}&rsquo;?{% endblocktrans %}

                <div class="ng-form-row ng-margin-top">
                    <input type="submit" class="ng-button ng-button-danger ng-float-right ng-margin-left" value="{% trans "Yes" %}" />
                    <a href="{% url "eventcalendar-edit-event" slug=object.slug %}" class="ng-button ng-float-right">{% trans "No" %}</a>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

eventcalendar/templates/eventcalendar/event_form.html
{% extends "eventcalendar/event_form_base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block pagetitle %}Create Event{% endblock %}

{% block extra_head %}
    {{ block.super }}
    {{ form.media }}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
    <script type="text/javascript" src="{% static "eventcalendar/inlines.js" %}"></script>
    <style type="text/css">
        .asteriskField {
            color: #f00;
        }
        .empty-form {
            display: none;
        }
        .inline-group {
            margin-top: 20px;
        }
        .inline-related + .inline-related {
            margin-top: 20px;
        }
        .inline-related fieldset + fieldset {
            margin-top: 20px;
        }
        .inline-deletelink {
            float: right;
            color: #F00;
        }
        .ng-form-icon-right {
            position: relative;
            display: inline-block;
            max-width: 100%;
        }
        .ng-form-icon-right>[class*='ng-icon-'],
        .ng-form-icon-right>[class='ng-close'] {
            position: absolute;
            top: 50%;
            right: 0;
            width: 30px;
            margin-top: -7px;
            font-size: 14px;
            color: #999;
            text-align: center;
            pointer-events: none;
        }
        .ng-form-icon-right>[class='ng-close'] {
            pointer-events: auto;
            margin-top: -10px;
        }
        .ng-form > fieldset {
            margin-top: 20px;
        }
        .ng-form fieldset .ng-form-row {
            margin-left:20px; margin-right: 20px;
        }
        table.hstore-rows {
            margin: 0;
        }
        .ng-form-help-block {
            color: #999;
        }
        .ng-list.schedule-dates {margin-top:0;}
  </style>
{% endblock extra_head %}

{% block body %}
    <div class="ng-width ng-container-center ng-margin-top" style="max-width: 500px">
        {% if form.errors %}
            <div class="ng-alert ng-alert-danger"><p>Please correct the errors below.</p></div>
            {{ form.errors }}
        {% endif %}
        <form class="ng-form ng-form-stacked" method="POST" {% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>

            {% crispy form form.form_helper %}

            {% for inline in inlines %}
            <div class="inline-group" id="{{ inline.prefix }}-group">
                <h3>{{ inline.prefix|capfirst }}</h3>
                {{ inline.management_form|crispy }}
                {{ inline.non_form_errors }}
                {% for formset in inline %}
                  {% include "eventcalendar/_schedule_inline.html" %}
                {% endfor %}

                {% include "eventcalendar/_schedule_inline.html" with formset=inline.empty_form schedule_helper=schedule_helper empty=True only %}

            </div>
            {% endfor %}
            <div class="ng-form-row ng-margin-top">
                {% if object.id %}<a href="{% url "eventcalendar-delete-event" slug=object.slug %}" class="ng-button ng-button-  danger ng-float-left" />{% trans "Delete" %}</a>{% endif %}

                <span class="ng-float-right">
                    <input type="button" class="ng-button" value="{% trans "Cancel" %}" />
                    <input type="submit" class="ng-button ng-button-success" value="{% trans "Save" %}">
                </span>
            </div>

        </form>
    </div>
    <script type="text/autocomplete" id="venue-autcomplete">{% verbatim %}
        <ul class="ng-nav ng-nav-autocomplete ng-autocomplete-results">
            {{~items}}
            <li data-value="{{ $item.name}}" data-id="{{ $item.id }}" data-address="{{ $item.address }}">
                <a>{{ $item.name }}</a>
            </li>
            {{/items}}
        </ul>
    {% endverbatim %}</script>
{% endblock body %}

{% block footer_js %}
    {{ block.super }}
    <script type="text/javascript">
    $('#id_age_range').on("change", function(){
        var $this = $(this),
            value = $this.prop("value").split(";");
        $("#id_min_age").val(value[0]);
        $("#id_max_age").val(value[1]);
    });
    $("#{{ inlines.0.prefix|escapejs }}-group .inline-related").stackedFormset({
        prefix: "{{ inlines.0.prefix|escapejs }}",
        deleteText: "{% filter escapejs %}{% trans "Remove" %}{% endfilter %}",
        addText: "{% filter escapejs %}{% blocktrans with verbose_name=inlines.0.opts.verbose_name|capfirst %}Add another schedule{% endblocktrans %}{% endfilter %}"
    });

    function showDates(container, dates) {
        var output = [],
            outstr = '';
        for (var i = 0; i < dates.length; i++) {
            if (dates[i] instanceof Date)
                output.push("<li>" + moment(dates[i]).format("ddd M-D-YYYY h:mm A") + "</li>");
            else
                output.push("<li>" + dates[i] + "</li>");
        };
        outstr = output.join("");
        container.html(outstr);
        $('.schedule-dates').html(outstr);
    }

    function handleRuleChange(eventObject) {
        var $target = $(eventObject.target),
            $container = $target.parents('.inline-related'),
            baseId = $container.attr('id'),
            $startDate = $("#id_" + baseId + "-begins_0"),
            $startTime = $("#id_" + baseId + "-begins_1"),
            $recurring = $("#id_" + baseId + "-schedule_text"),
            $rrule = $("#id_" + baseId + "-rrule_str"),
            text = $recurring.val(),
            startDate = $startDate.val(),
            startTime = $startTime.val(),
            max = 30,
            dates,
            rule,
            opts,
            $scheduleDates = $container.find(".schedule-dates");
        opts = RRule.parseText(text);
        if (opts){
            rule = RRule.fromText(text);
            opts = rule.origOptions
        } else {
            opts = {count: 1, freq: 2, byweekday: null}
        }
        opts.dtstart = new Date(startDate + " " + startTime);
        try {
            rule = new RRule(opts);
            $rrule.val(rule.toString());

            dates = rule.all(function(date, i) {
                if (!rule.options.count && i === max) {return false;}
                return true;
            })

            if (dates.length === max) dates.push("&hellip;");
            showDates($scheduleDates, dates);
        } catch(e) {}
    }

    $(document).ready(function() {
        $("#id_schedules-0-schedule_text").change(handleRuleChange);
        $("#id_schedules-0-begins_0").change(handleRuleChange);
        $("#id_schedules-0-begins_1").change(handleRuleChange);
        var autoElem = $("#div_id_location_name");
        autoElem.addClass('ng-position-relative');
        var autocomplete = NGkit.autocomplete(autoElem, {source: "/events/venues/", template: $("#venue-autcomplete").html()});
        handleRuleChange({target: $('#id_schedules-0-begins_0')});
    });

    $(document).on("selectitem.ng.autocomplete", function(event, data, acobject) {
        var venue = document.getElementById('id_venue'),
            raw_l = document.getElementById('id_raw_location');
        if (data.id) venue.value = data.id;
        if (data.address) raw_l.value = data.address;
        $("#div_id_location_name .ng-close").removeClass('ng-hidden');
    });
    $("#div_id_location_name .ng-close").on('click', function(event) {
        $("#id_venue").val("");
        $("#id_raw_location").val("");
        $("#id_location_name").val("");
        $("#div_id_location_name .ng-close").addClass('ng-hidden');
    });
    $(document).on("inline.add", function setupNewInline(event) {
        var numforms = $("#id_{{ inlines.0.prefix }}-TOTAL_FORMS").val(),
            numforms_zero = numforms - 1,
            $row = $(event.target);
        $row.find(".inline-number").append(numforms);
        $("#id_schedules-" + numforms_zero + "-duration").ionRangeSlider();
        $("#id_schedules-" + numforms_zero + "-schedule_text").change(handleRuleChange);
        $("#id_schedules-" + numforms_zero + "-begins_0").change(handleRuleChange);
        $("#id_schedules-" + numforms_zero + "-begins_1").change(handleRuleChange);
    });
    </script>

{% endblock footer_js %}

eventcalendar/templates/eventcalendar/event_form_base.html
{% extends "eventcalendar/base.html" %}