eventcalendar/urls.py
from django.conf.urls import patterns, url
import views


urlpatterns = patterns('',
    # url(
    #     r'^$',
    #     views.OccurrenceList.as_view(),
    #     name='eventcalendar-index'
    # ),
    url(
        r'^$',
        views.OccurrenceSearchView.as_view(),
        name='eventcalendar-index'
    ),
    url(
        r'^parse/$',
        views.parsable,
        name='eventcalendar-parsable',
    ),
    url(
        r'^venues/$',
        views.VenueList.as_view(),
        name='eventcalendar-venue-list'
    ),
    url(
        r'^event/add/$',
        views.EventCreate.as_view(),
        name='eventcalendar-add-event'
    ),
    url(
        r'^event/(?P<slug>[-\w]+)/$',
        views.EventView.as_view(),
        name='eventcalendar-event'
    ),
    url(
        r'^event/(?P<slug>[-\w]+)/edit/$',
        views.EventUpdate.as_view(),
        name='eventcalendar-edit-event'
    ),
    url(
        r'^event/(?P<slug>[-\w]+)/delete/$',
        views.EventDelete.as_view(),
        name='eventcalendar-delete-event'
    ),
    url(
        r'^(?P<slug>[\w-]+)/$',
        views.EventCategoryDetail.as_view(),
        name='eventcalendar-category'
    ),
    # url(
    #     r'^(?P<slug>[-\w]+)/(\d+)/$',
    #     views.occurrence_view,
    #     name='eventcalendar-occurrence'
    # ),
)

eventcalendar/forms.py
"""
Convenience forms for adding and updating ``Event`` and ``Occurrence``s.

"""
from __future__ import print_function, unicode_literals

from django import VERSION
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify
from django.forms.utils import to_current_timezone

from django_hstore.forms import DictionaryField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, HTML
from haystack.forms import FacetedSearchForm

from .settings import TIMESLOT_INTERVAL, DEFAULT_OCCURRENCE_DURATION
from .models import Event, Schedule, Venue
from .fields import SliderWidget, RangeField, FrontEndHStoreWidget, ClearableWidget
import utils

FIELDS_REQUIRED = (VERSION[:2] >= (1, 6))
MINUTES_INTERVAL = TIMESLOT_INTERVAL.seconds // 60
SECONDS_INTERVAL = utils.time_delta_total_seconds(DEFAULT_OCCURRENCE_DURATION)


class CustomSplitDateTimeWidget(forms.MultiWidget):
    """
    A Widget that splits datetime input into two <input type="text"> boxes.
    """
    supports_microseconds = False

    def __init__(self, attrs=None, date_format=None, time_format=None):
        date_attrs = attrs or {}
        time_attrs = attrs or {}
        date_attrs['type'] = 'text'
        date_attrs['data-ng-datepicker'] = ''
        time_attrs['type'] = 'text'
        time_attrs['data-ng-timepicker'] = "{format: '12h'}"

        widgets = (forms.DateInput(attrs=date_attrs, format=date_format),
                   forms.TimeInput(attrs=time_attrs, format=time_format))
        super(CustomSplitDateTimeWidget, self).__init__(widgets, attrs)

    def decompress(self, value):
        if value:
            value = to_current_timezone(value)
            return [value.date(), value.time().replace(microsecond=0)]
        return [None, None]


class MultipleIntegerField(forms.MultipleChoiceField):
    """
    A form field for handling multiple integers.

    """
    def __init__(self, choices, size=None, label=None, widget=None):
        if widget is None:
            widget = forms.SelectMultiple(attrs={'size': size or len(choices)})
        super(MultipleIntegerField, self).__init__(
            required=False,
            choices=choices,
            label=label,
            widget=widget,
        )

    def clean(self, value):
        return [int(i) for i in super(MultipleIntegerField, self).clean(value)]


class ScheduleFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(ScheduleFormHelper, self).__init__(*args, **kwargs)
        self.form_method = 'post'
        self.form_tag = False
        self.recurring_id = "id_schedules-__prefix__-recurring"
        self.layout = Layout(
            'id',
            Fieldset(
                'Date and Time Information',
                'begins',
                'duration',
            ),
            Fieldset(
                'Optional Recurring Options',
                HTML("""<div class="ng-grid"><div class="ng-width-6-10">"""),
                'schedule_text',
                'rrule_str',
                HTML("""<p>Examples:</p><ul class="ng-list ng-list-bullet">
                    <li>Every weekday</li>
                    <li>Every 2 weeks on Tuesday</li>
                    <li>Every week on Monday, Wednesday</li>
                    <li>Every month on the 2nd last Friday for 7 times</li>
                    <li>Every 6 months</li></ul>"""),
                HTML("""</div>
                        <div class="ng-width-4-10">
                            <fieldset>
                                <legend class="ng-padding-small-bottom">Schedule Dates</legend>
                                <ul class="schedule-dates ng-list ng-list-striped">
                                </ul>
                            </fieldset>
                        </div>
                    </div>"""),
                css_id=self.recurring_id
            ),
        )


class ScheduleForm(forms.ModelForm):
    """
    Schedule Form with just a text field
    """
    begins = forms.SplitDateTimeField(
        label=_('Begins'),
        widget=CustomSplitDateTimeWidget())
    duration = forms.DecimalField(
        label=_("Duration in hours"),
        widget=SliderWidget(
            min_value=0,
            max_value=24,
            attrs={
                'data-step': '0.5',
                'data-grid-num': '6',
            }),
        initial=1
    )
    schedule_text = forms.CharField(
        label="Type in the recurring schedule",
        widget=forms.TextInput(),
        required=False)
    rrule_str = forms.CharField(
        widget=forms.HiddenInput(),
        required=False)

    class Meta:
        model = Schedule
        fields = '__all__'

    class Media:
        js = ('eventcalendar/nlp.js', 'eventcalendar/rrule.js', )


class EventForm(forms.ModelForm):
    """
    A simple form for adding and updating Event attributes
    """
    required_css_class = "ng-form-required"
    error_css_class = "ng-form-danger"
    id = forms.CharField(widget=forms.HiddenInput(), required=False)
    more_info_url = forms.URLField(widget=forms.TextInput(), required=False)
    tickets_url = forms.URLField(widget=forms.TextInput(), required=False)
    min_age = forms.IntegerField(widget=forms.HiddenInput(), required=False, initial=0)
    max_age = forms.IntegerField(widget=forms.HiddenInput(), required=False, initial=100)
    age_range = RangeField(forms.IntegerField, min_value=0, max_value=100, required=False)
    price_info = DictionaryField(widget=FrontEndHStoreWidget, required=False, help_text="Give each price a label for the price such as &lsquo;Adult&rsquo; or &lsquo;Matinee&rsquo;.")
    location_name = forms.CharField(required=False, widget=ClearableWidget(attrs={'class': "textinput textInput ng-width-1-1"}))
    raw_location = forms.CharField(label="Location address", required=True)
    venue = forms.ModelChoiceField(
        queryset=Venue.objects.all(),
        widget=forms.HiddenInput,
        required=False)

    class Meta:
        model = Event
        fields = (
            "id", "title", "category", "description", "location_name", "raw_location",
            "venue", "image",
            "age_range", "more_info_url", "tickets_url", "price_info",
            "min_age", "max_age")

    def __init__(self, *args, **kwargs):
        if 'instance' in kwargs and kwargs['instance']:
            kwargs['initial']['age_range'] = "%s;%s" % (kwargs['instance'].min_age, kwargs['instance'].max_age, )
        super(EventForm, self).__init__(*args, **kwargs)
        self.form_helper = FormHelper()
        self.form_helper.form_tag = False
        self.form_helper.layout = Layout(
            'id',
            Fieldset(
                'Event Information',
                'id',
                'title',
                'category',
                'description'),
            Fieldset(
                'Location Information',
                'location_name',
                'raw_location',
                'venue'),
            Fieldset(
                'Additional Information',
                'more_info_url',
                'tickets_url',
                'price_info',
                'age_range',
                'image',
                'min_age',
                'max_age',
            )
        )

    def clean(self):
        cleaned_data = super(EventForm, self).clean()
        title = cleaned_data.get('title', '')
        cleaned_data['slug'] = slugify(title)
        return cleaned_data


class OccurrenceSearchForm(FacetedSearchForm):
    start_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'type': 'date'}))
    end_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'type': 'date'}))
    address = forms.CharField(required=False)
    distance = forms.ChoiceField(
        choices=(
            ('5', '5 miles'),
            ('10', '10 miles'),
            ('25', '25 miles'),
            ('50', '50 miles'),
        ),
        initial='5',
        required=False
    )
    use_current_location = forms.BooleanField(required=False, initial=False)
    latitude = forms.CharField(required=False, widget=forms.HiddenInput)
    longitude = forms.CharField(required=False, widget=forms.HiddenInput)
    neighborhoods = forms.MultipleChoiceField(
        required=False,
        choices=()
    )
    categories = forms.MultipleChoiceField(
        required=False,
        choices=()
    )
    # sorting = forms.ChoiceField(
    #     choices=(
    #         ('start_time', 'Date'),
    #         ('proximity', 'Proximity'),
    #         ('-score', 'Relevance'), ),
    #     initial='start_time',
    #     required=False,
    #     widget=forms.HiddenInput
    # )

    def __init__(self, *args, **kwargs):
        super(OccurrenceSearchForm, self).__init__(*args, **kwargs)

        # Setup dynamic choices
        from .models import Neighborhood, EventCategory
        from django.core.cache import caches
        cache = caches['default']
        neighborhoods = cache.get('eventcalendar_neighborhoods')
        if not neighborhoods:
            neighborhoods = list(Neighborhood.objects.values_list('slug', 'name'))
            cache.set('eventcalendar_neighborhoods', neighborhoods, 3600)
        categories = cache.get('eventcalendar_categories')
        if not categories:
            categories = list(EventCategory.objects.values_list('slug', 'name'))
            cache.set('eventcalendar_neighborhoods', categories, 3600)
        self.fields['neighborhoods'].choices = neighborhoods
        self.fields['categories'].choices = categories

        # Set up faceting
        self.searchqueryset = self.searchqueryset.order_by('start_time')
        self.searchqueryset = self.searchqueryset.facet('neighborhood')
        self.searchqueryset = self.searchqueryset.facet('category')
        self.location = None

    def no_query_found(self):
        """
        Determines the behavior when no query was found.

eventcalendar/templates/_widgets/_calendar_pagination.html
<div class="ng-margin-bottom" id="date-paginator" data-ng-sticky></div>

eventcalendar/templates/_widgets/_filter.html
{# Required vars: form #}

<form class="ng-form ng-form-horizontal" id="filterform" method="GET" action="">
    <div class="ng-form-icon ng-width-1-1">
        <i class="ng-icon-search"></i>
        <input name="{{ form.q.name }}" id="{{ form.q.id_for_label }}" class="ng-width-1-1" type="search" placeholder="Search for..." style="box-sizing: border-box">
    </div>
    <div data-ng-accordion="{target:'#advancedfilter'}" class="ng-margin-small-top">
        <a href="" class="ng-unstyled"><i class="ng-icon-disclosure"></i> <i class="ng-icon-sliders"></i> Advanced Filtering</a>
    </div>
    <div id="advancedfilter" class="ng-hidden ng-panel ng-panel-box">
        <div class="ng-form-row">
            <label class="ng-form-label" for="id_start_date">Between</label><div class="ng-form-controls">{{ form.start_date }} and {{ form.end_date }}</div>
        </div>
        <div class="ng-form-row">
            <label class="ng-form-label" for="id_distance">Within</label> <div class="ng-form-controls ng-form-controls-text">{{ form.distance }} from {{ form.address }} or {{ form.use_current_location }} <label for="id_use_current_location">Use current location</label>{{ form.latitude}} {{ form.longitude }}</div>
        </div>
        <div class="ng-form-row">
            <label class="ng-form-label" for="id_neighborhoods">Neighborhoods</label> <div class="ng-form-controls">{{ form.neighborhoods }}</div>
        </div>
        <div class="ng-form-row">
            <label class="ng-form-label" for="id_categories">Categories</label> <div class="ng-form-controls">{{ form.categories }}</div>
        </div>
    </div>
</form>

eventcalendar/templates/_widgets/_filter_js.html
{% load static from staticfiles %}
<script type="text/javascript" src="{% static "eventcalendar/moment.min.js" %}"></script>
<script type="text/javascript" src="{% static "select2/dist/js/select2.min.js" %}"></script>
<script type="text/javascript">
    function parseQS() {
        var vars = [],
            hash;
        var q = document.URL.split('?')[1];
        if (q !== undefined) {
            q = q.split('&');
            for(var i = 0; i < q.length; i++){
                hash = q[i].split('=');
                vars.push(hash[1]);
                vars[hash[0]] = hash[1];
            }
        }
        return vars;
    }
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?

                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    $.ajaxSetup({
         beforeSend: function(xhr, settings) {
             if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                 // Only send the token to relative URLs i.e. locally.
                 xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
             }
         }
    });
    function submitFilterForm() {
        var formData = $('#filterform').serialize();
        $.get(window.location, formData, function(data, textStatus, xhr) {
            $("#searchresults").html(data.html);
            $('[data-ng-grid]').each(function(){
                var ele = $(this);
                if(!ele.data("grid")) {
                    var plugin = NGkit.grid(ele, NGkit.Utils.options(ele.attr('data-ng-grid')));
                }
            });
        });
    }
    $(function() {
        var qsVars = parseQS(),
            startDate = moment().format('YYYY-MM-DD'),
            selectedDate = qsVars.start_date || startDate;
        $('#filterform input, #filterform select').on('change', function(event) {
            if ("geolocation" in navigator && $('#id_use_current_location').prop("checked")) {
                navigator.geolocation.getCurrentPosition(function(position) {
                    var lat = position.coords.latitude.toString(),
                        lon = position.coords.longitude.toString();
                    $('#id_latitude').val(lat);
                    $('#id_longitude').val(lon);
                    submitFilterForm();
                });
            } else {
                $('#id_latitude').val("");
                $('#id_longitude').val("");
                submitFilterForm();
            }
        });
        $(document).on('ng-open', function(event){
            $('#id_neighborhoods').select2();
            $('#id_categories').select2();
        });
    });
</script>

eventcalendar/templates/_widgets/_occurrence_tile.html
{% load humanize %}
{# requires variables: object, include_date #}
<div> {# This gets the styling for the automatic layout#}
    <div class="ng-panel ng-panel-card" itemscope itemtype="http://schema.org/{{ object.event.category.event_type }}">
        {% if object.image %}<div class="ng-panel-teaser">
            <a href="{{ object.event_url }}">
                <img src="{{ object.image }}" width="490" height="277" alt="{{ object.title }}" />
            </a>
        </div>{% endif %}
        <h3 class="ng-panel-title"><a href="{{ object.event_url }}" itemprop="url"><span itemprop="name">{{ object.title }}</span></a></h3>
        <p class="ng-margin-bottom-remove" itemprop="startDate" datetime="{{ object.start_time.isoformat }}">{% if include_date %}{{ object.start_time|naturalday:"n-j-Y"|capfirst }} @{% endif %} {{ object.start_time|date:"P" }}</p>
        <div class="location" itemprop="location" itemscope itemtype="address">
            {% if object.location_name %}<p class="ng-margin-bottom-remove ng-text-bold" itemprop="name">{{ object.location_name }}</p>{% endif %}
            <p class="ng-margin-remove">{% if object.parsable_address %}<span itemprop="streetAddress">{{ object.street_address }}</span>, <span itemprop="addressLocality">{{ object.city }}</span>, <span itemprop="addressRegion">{{ object.state }}</span> <span itemprop="postalCode">{{ object.zipcode }}</span>{% else %}{{ object.raw_location }}{% endif %}</p>
        </div>
    </div>
</div>

eventcalendar/templates/_widgets/_occurrence_tile_by_date.html
{# requires variable: object_list #}

<div> {# Just to offset the closing div in the ifchanged block #}
{% for occurrence in object_list %}
    {% ifchanged %}
        </div>
        <h3>{{ occurrence.start_time|date:"l F j, Y" }}</h3>
        <div class="ng-grid-width-small-1-2 ng-grid-width-medium-1-3 ng-margin-top" data-ng-grid="{gutter: 20}" id="event-list-{{ occurrence.start_time|date:"Y-m-d" }}">
    {% endifchanged %}
    {% include "_widgets/_occurrence_tile.html" with object=occurrence include_date=True %}
    {% if forloop.last %}</div>{% endif %}
{% endfor %}
</div>